data:
  class_path: anomalib.data.MVTec
  init_args:
    category: bottle
    eval_batch_size: 32
    image_size:
    - 256
    - 256
    num_workers: 0
    root: ./data
    train_batch_size: 32
early_stopping:
  enabled: true
  min_delta: 0.01
  mode: min
  monitor: train_loss
  patience: 10
  verbose: true
logging:
  log_graph: false
  logger: []
metrics:
  image:
  - F1Score
  - AUROC
  - AUPR
  pixel:
  - F1Score
  - AUROC
  - AUPR
  threshold:
    class_path: anomalib.metrics.F1AdaptiveThreshold
    init_args:
      default_value: 0.5
model:
  class_path: anomalib.models.Fre
  init_args:
    backbone: resnet50
    input_dim: 65536
    latent_dim: 100
    layer: layer3
    pooling_kernel_size: 2
    pre_trained: true
normalization:
  normalization_method: min_max
project:
  path: ./results
  seed: 42
  unique_dir: false
trainer:
  accelerator: auto
  accumulate_grad_batches: 1
  check_val_every_n_epoch: 5
  default_root_dir: results/fre
  devices: 1
  enable_checkpointing: true
  enable_progress_bar: true
  fast_dev_run: false
  gradient_clip_algorithm: norm
  gradient_clip_val: 0
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  max_epochs: 50
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  num_nodes: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  strategy: null
  sync_batchnorm: false
  track_grad_norm: -1
  val_check_interval: 5
visualization:
  image_save_path: null
  log_images: false
  mode: full
  save_images: false
  show_images: false
